//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxPivotGrid_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxPivotGrid_v13_1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxPivotGrid_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [Bottom Panel Only 1 by 4 Layout] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_BottomPanelOnly1by4Layout {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_BottomPanelOnly1by4Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Bottom Panel Only 2 by 2 Layout] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_BottomPanelOnly2by2Layout {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_BottomPanelOnly2by2Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Collapse] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Column Area Headers] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_ColumnAreaHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_ColumnAreaHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Data Area Headers] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_DataAreaHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_DataAreaHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_DragHideField {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_DragHideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Expand] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Hidden Field&apos;s Headers] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_FieldListHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FieldListHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Filter Area Headers] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterAreaHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterAreaHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Filter] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterButton {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Filtered] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterButtonActive {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Resize] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterWindowSizeGrip {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterWindowSizeGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Layout Button] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_LayoutButton {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_LayoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Row Area Headers] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_RowAreaHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_RowAreaHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Ascending) 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Descending) 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Stacked Default Layout] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_StackedDefaultLayout {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_StackedDefaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Stacked Side By Side Layout] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_StackedSideBySideLayout {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_StackedSideBySideLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Top Panel Only Layout] 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Alt_TopPanelOnlyLayout {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_TopPanelOnlyLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This command cannot be used on multiple selections. 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CannotCopyMultipleSelections {
            get {
                return ResourceManager.GetString("PivotGridStringId.CannotCopyMultipleSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CellError {
            get {
                return ResourceManager.GetString("PivotGridStringId.CellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Area 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_ColumnArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.ColumnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop Column Fields Here 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_ColumnHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.ColumnHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormAddTo {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormAddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose fields to add to report: 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormAvailableFields {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormAvailableFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Areas Section Only (1 by 4) 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormBottomPanelOnly1by4 {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormBottomPanelOnly1by4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Areas Section Only (2 by 2) 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormBottomPanelOnly2by2 {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormBottomPanelOnly2by2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PivotGrid Field List 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defer Layout Update 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormDeferLayoutUpdate {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormDeferLayoutUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden Fields 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormHiddenFields {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormHiddenFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag fields between areas below: 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormHint {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customization Form Layout 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormLayoutButtonTooltip {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormLayoutButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a field here to customize layout 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormListBoxText {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormListBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fields Section and Areas Section Stacked 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormStackedDefault {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormStackedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fields Section and Areas Section Side-By-Side 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormStackedSideBySide {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormStackedSideBySide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag Items to the PivotGrid 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormText {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fields Section Only 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormTopPanelOnly {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormTopPanelOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormUpdate {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Area 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_DataArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_DataFieldCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataFieldCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop Data Items Here 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_DataHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error retrieving drilldown dataset 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_DrillDownException {
            get {
                return ResourceManager.GetString("PivotGridStringId.DrillDownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Prefilter 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_EditPrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.EditPrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Area 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_FilterArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Blank) 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_FilterBlank {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_FilterCancel {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop Filter Fields Here 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_FilterHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert Filter 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_FilterInvert {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_FilterOk {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Show All) 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_FilterShowAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Show Blanks) 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_FilterShowBlanks {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterShowBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grand Total 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_GrandTotal {
            get {
                return ResourceManager.GetString("PivotGridStringId.GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Details command cannot be executed when multiple items are selected in a report filter field. Select a single item for each field in the report filter area before performing a drillthrough. 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPDrillDownFilterException {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPDrillDownFilterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KPIs 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPKPIsCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPKPIsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goal 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPKPITypeGoal {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPKPITypeGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPKPITypeStatus {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPKPITypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trend 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPKPITypeTrend {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPKPITypeTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPKPITypeValue {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPKPITypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPKPITypeWeight {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPKPITypeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measures 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPMeasuresCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPMeasuresCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In order to use the PivotGrid OLAP functionality, you should have a MS OLAP OleDb provider installed on your system.
        ///You can download it here: 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_OLAPNoOleDbProvidersMessage {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPNoOleDbProvidersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Sorting 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuClearSorting {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuCollapse {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse All 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuCollapseAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuExpand {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand All 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuExpandAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuFieldOrder {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuFieldOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHideField {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Field List 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHideFieldList {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHideFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Prefilter 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHidePrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHidePrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KPI Graphics 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphic {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cylinder 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicCylinder {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Faces 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicFaces {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gauge 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicGauge {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicNone {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reversed Cylinder 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicReversedCylinder {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicReversedCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reversed Gauge 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicReversedGauge {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicReversedGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reversed Status Arrow 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicReversedStatusArrow {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicReversedStatusArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reversed Thermometer 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicReversedThermometer {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicReversedThermometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Road Signs 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicRoadSigns {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicRoadSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Defined 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicServerDefined {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicServerDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shapes 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicShapes {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Arrow 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicStandardArrow {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicStandardArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status Arrow 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicStatusArrow {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicStatusArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thermometer 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicThermometer {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicThermometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traffic Lights 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicTrafficLights {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicTrafficLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variance Arrow 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuKPIGraphicVarianceArrow {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuKPIGraphicVarianceArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move to Beginning 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoBeginning {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move to End 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoEnd {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move to Left 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoLeft {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move to Right 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoRight {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Data 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuRefreshData {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuRefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove All Sorting 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuRemoveAllSortByColumn {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuRemoveAllSortByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression Editor... 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuShowExpression {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuShowExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Field List 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuShowFieldList {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuShowFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Prefilter 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuShowPrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuShowPrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort A-Z 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortAscending {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Z-A 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortDescending {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort &quot;{0}&quot; by This Column 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortFieldByColumn {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortFieldByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort &quot;{0}&quot; by This Row 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortFieldByRow {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortFieldByRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PivotGrid Prefilter 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrefilterFormCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrefilterFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurs in the Prefilter criteria. Please detect invalid property captions inside the criteria operands and correct or remove them. 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrefilterInvalidCriteria {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrefilterInvalidCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (invalid property) 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrefilterInvalidProperty {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrefilterInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print Designer 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesigner {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryDefault {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Values 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Headers 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lines 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Headers 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerColumnHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Headers 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerDataHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerDataHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Headers 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerFilterHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerFilterHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Headers On Every Page 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerHeadersOnEveryPage {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerHeadersOnEveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal Lines 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerHorizontalLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerHorizontalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Column Field Values 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerMergeColumnFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerMergeColumnFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Row Field Values 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerMergeRowFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerMergeRowFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerPageBehavior {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerPageBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerPageOptions {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerPageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Headers 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerRowHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerRowHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unused Filter Fields 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerUnusedFilterFields {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerUnusedFilterFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Print Appearance 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerUsePrintAppearance {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerUsePrintAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Lines 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerVerticalLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerVerticalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Area 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_RowArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.RowArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop Row Fields Here 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_RowHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.RowHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SearchBoxText {
            get {
                return ResourceManager.GetString("PivotGridStringId.SearchBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_StatusBad {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Good 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_StatusGood {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neutral 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_StatusNeutral {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryAverage {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryCount {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryCustom {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply to specific level 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterApplyToSpecificLevel {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterApplyToSpecificLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterClearButton {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column field: 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterColumnField {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterColumnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Values 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterLabelValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterLabelValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterLegendHidden {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterLegendHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterLegendVisible {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterLegendVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Count 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterMaxValueCount {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterMaxValueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Visible Count 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterMaxVisibleCount {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterMaxVisibleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show values from 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterRangeFrom {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterRangeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterRangeTo {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterRangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row field: 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryFilterRowField {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryFilterRowField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryMax {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryMin {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StdDev 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryStdDev {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StdDevp 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryStdDevp {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryStdDevp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummarySum {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummarySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Var 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryVar {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Varp 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_SummaryVarp {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryVarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TopValueOthersRow {
            get {
                return ResourceManager.GetString("PivotGridStringId.TopValueOthersRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_Total {
            get {
                return ResourceManager.GetString("PivotGridStringId.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Total 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormat {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Average 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatAverage {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Count 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatCount {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Custom 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatCustom {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Max 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatMax {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Min 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatMin {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} StdDev 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatStdDev {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} StdDevp 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatStdDevp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatStdDevp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Sum 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatSum {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Var 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatVar {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Varp 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TotalFormatVarp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatVarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Going Down 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TrendGoingDown {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendGoingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Going Up 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TrendGoingUp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendGoingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Change 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_TrendNoChange {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string PivotGridStringId_ValueError {
            get {
                return ResourceManager.GetString("PivotGridStringId.ValueError", resourceCulture);
            }
        }
    }
}
