//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_v13_1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 No data to display 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_DataViewBase_EmptyDataText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataViewBase_EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page size: 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerPageSize {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rows per page: 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerRowPerPage {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerRowPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All pages 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerSummaryAllPages {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerSummaryAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0} of {1} 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerSummaryFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Cancel {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_DeleteConfirm {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access prohibited. The operation cannot be completed 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorAccessProhibited {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorAccessProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified file/folder already exists 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorAlreadyExists {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder not found 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorFolderNotFound {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This name contains invalid characters. The operation cannot be completed 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorInvalidSymbols {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorInvalidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unspecified IO error. The operation cannot be completed 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorIO {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file/folder name cannot be empty 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access denied. The operation cannot be completed 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorNoAccess {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unspecified error 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorOther {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The root folder is not specified or does not exist 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorRootFolderNotSpecified {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorRootFolderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No access to the thumbnail folder 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorThumbnail {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The upload was unsuccessful for {0} of {1} files 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorUploadSeveralFiles {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorUploadSeveralFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation cannot be completed because the file/folder is being used by another process 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorUsedByAnotherProcess {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorUsedByAnotherProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file extension is not allowed. The operation cannot be completed 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorWrongExtension {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FileInfoTypeCaption_FileName {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FileInfoTypeCaption_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date modified 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FileInfoTypeCaption_LastWriteTime {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FileInfoTypeCaption_LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FileInfoTypeCaption_Size {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FileInfoTypeCaption_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by: 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Filter {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Folder {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locked for upload 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FolderLocked {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FolderLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 30 days 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_DateMonth {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_DateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_DateToday {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_DateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 7 days 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_DateWeek {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_DateWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 365 days 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_DateYear {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_DateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty ({0}) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeEmpty {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gigantic ({0}) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeGigantic {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeGigantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Huge ({0}) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeHuge {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeHuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large ({0}) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeLarge {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium ({0}) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeMedium {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small ({0}) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeSmall {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tiny ({0}) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeTiny {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeTiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Destination Folder 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_MovePopupHeader {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_MovePopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Ok {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path: 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Path {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create (F7) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbCreate {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete (Del) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbDelete {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbDownload {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move (F6) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbMove {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbRefresh {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename (F2) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbRename {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading&amp;hellip; 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Loading {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to top 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_NewsControl_BackToTop {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.NewsControl_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page: 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_NewsControl_Page {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.NewsControl_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_All {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_First {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Last {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Next {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page size: 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_PageSize {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_PageSizeAllItem {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_PageSizeAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Prev {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pages: {0} - {1} ({2} items) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_SummaryAllPagesFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_SummaryAllPagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0} of {1} ({2} items) 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_Pager_SummaryFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_SummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Close] 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_CloseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Collapse/Expand] 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_CollapseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_CollapseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Maximize/Restore] 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_MaximizeButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_MaximizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Pin/Unpin] 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_PinButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_PinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Refresh] 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_RefreshButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Resize] 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_SizeGrip {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_SizeGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Back to Top] 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_BackToTop {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter:&amp;nbsp;&amp;nbsp;&amp;nbsp; 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_FilterCaption {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_FilterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;?&lt;/b&gt; = any single character
        ///&lt;b&gt;*&lt;/b&gt; = any characters 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_FilterHint {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data for this filter criteria 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_NoData {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_TreeView_AltCollapse {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TreeView_AltCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_TreeView_AltExpand {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TreeView_AltExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_TreeView_AltLoading {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TreeView_AltLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access to the server path &quot;{0}&quot; is denied. The reason might be due to lack of permissions to write files in this (or parent) folder. 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_AccessDeniedError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_AccessDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_AddButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_BrowseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_CancelButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear selection 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_ClearFileSelectionButtonToolTip {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_ClearFileSelectionButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File uploading fails because the form&apos;s enctype attribute is not set to &apos;multipart/form-data&apos; 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_EnctypeError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_EnctypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The uploading file doesn&apos;t exist 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_FileDoesNotExistError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_FileDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File upload failed due to an external error 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_GeneralError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file path &quot;{0}&quot; isn&apos;t a valid Windows path. 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_InvalidWindowsPath {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_InvalidWindowsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File size exceeds the maximum allowed size, which is {0} bytes 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_MaxSize {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attention! 
        ///
        ///The following {0} files are invalid because they exceed the allowed file size ({1}) or their extensions are not allowed. These files have been removed from selection, so they will not be uploaded. 
        ///
        ///{2} 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_MultiSelection {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_MultiSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This content type isn&apos;t allowed 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_NotAllowedContentTypes {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_NotAllowedContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file extension isn&apos;t allowed 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_NotAllowedFileExtension {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_NotAllowedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_RemoveButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} files are selected for upload 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_SelectedSeveralFiles {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_SelectedSeveralFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please install &lt;a href=&quot;{0}&quot;&gt;Microsoft Silverlight v3 or later&lt;/a&gt; to view this content and have an ability to upload files. 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_SilverlightPluginLink {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_SilverlightPluginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many files are selected. Reduce the number of selected files and try again. 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_TooManyFilesError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_TooManyFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The server encountered an internal unspecified error that prevented it from fulfilling the request. 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_UnspecifiedError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_UploadButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File upload was canceled. 的本地化字符串。
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_UploadWasCanceledError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_UploadWasCanceledError", resourceCulture);
            }
        }
    }
}
