//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_XtraReports_v13_1_Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_XtraReports_v13_1_Web() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_XtraReports_v13_1_Web", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Csv 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_csv {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Html 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_html {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mht 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_mht {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_mht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pdf 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_pdf {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_png {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rtf 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_rtf {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_txt {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xls 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_xls {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xlsx 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_xlsx {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ParametersPanel_False {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ParametersPanel_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ParametersPanel_Reset {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ParametersPanel_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ParametersPanel_Submit {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ParametersPanel_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ParametersPanel_True {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ParametersPanel_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Cancel {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match case 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Case {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Case_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Case_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Down {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Down_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Down_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Next 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_FindNext {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find&amp;nbsp;what 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_FindWhat {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_FindWhat_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_FindWhat_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished searching the document. 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Finished {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Header {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Up {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Up_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Up_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match whole word only 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_WholeWord {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_WholeWord_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_WholeWord_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Page 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_FirstPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Page 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_LastPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Page 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_NextPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_OfLabel {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_OfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_PageLabel {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Page 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_PreviousPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print the current page 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_PrintPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_PrintPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print the report 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_PrintReport {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export a report and save it to the disk 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_SaveToDisk {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_SaveToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export a report and show it in a new window 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_SaveToWindow {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_SaveToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display the search window 的本地化字符串。
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_Search {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_Search", resourceCulture);
            }
        }
    }
}
