//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxEditors_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxEditors_v13_1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxEditors_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Clear {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Today {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The submitted code is incorrect 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Captcha image 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultImageAlternateText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultImageAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type the code shown: 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultTextBoxLabelText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultTextBoxLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show another code 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_RefreshText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checked 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_CheckBox_Checked {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.CheckBox_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unchecked 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_CheckBox_Unchecked {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.CheckBox_Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ? 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_CheckBox_Undefined {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.CheckBox_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;lt;empty&amp;gt; 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterConrol_Empty {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterConrol_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;lt;enter a value&amp;gt; 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterConrol_EmptyEnter {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterConrol_EmptyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Condition 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddCondition {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds a new condition to this group 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddConditionHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddConditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Group 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddGroup {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds a new item to the list 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddValueHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_BetweenAnd {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_BetweenAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equals,Does not equal,Is greater than,Is greater than or equal to,Is less than,Is less than or equal to,Is between,Is not between,Contains,Does not contain,Begins with,Ends with,Is like,Is not like,Is blank,Is not blank,Is any of,Is none of 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ClauseType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ClauseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And,Or,Not And,Not Or 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_GroupType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Not {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Builder 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_PopupHeaderText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_PopupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Remove {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removes this condition 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_RemoveConditionHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_RemoveConditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Filter 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ShowFilterControl {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ShowFilterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regular expression validation failed 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_RegExValidationErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.RegExValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_RequiredFieldErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.RequiredFieldErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrement 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_TrackBar_Decrement {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.TrackBar_Decrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_TrackBar_Drag {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.TrackBar_Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increment 的本地化字符串。
        /// </summary>
        internal static string ASPxEditorsStringId_TrackBar_Increment {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.TrackBar_Increment", resourceCulture);
            }
        }
    }
}
