//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxTreeList_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxTreeList_v13_1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxTreeList_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [Collapse] 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Expand] 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Ascending) 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Descending) 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete? 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Chooser 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Form 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_PopupEditFormCaption {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.PopupEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The node has descendant nodes. 的本地化字符串。
        /// </summary>
        internal static string ASPxTreeListStringId_RecursiveDeleteError {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.RecursiveDeleteError", resourceCulture);
            }
        }
    }
}
