//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxGridView_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxGridView_v13_1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxGridView_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [Collapse] 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Expand] 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Condition] 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_FilterRowButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_FilterRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Filter] 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Filtered] 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButtonActive {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Ascending) 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Descending) 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begins with 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterBeginsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterContains {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Doesn&apos;t contain 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterDoesNotContain {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ends with 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEndsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equals 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEquals {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreater {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than or equal to 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreaterOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLess {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than or equal to 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLessOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Like (&apos;%&apos;, &apos;_&apos;) 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLike {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two wildcard symbols are supported:
        /// &apos;%&apos; substitutes zero or more characters;
        /// &apos;_&apos; substitutes a single character. 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLikeToolTip {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLikeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Doesn&apos;t equal 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterNotEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_CommandClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelect {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete? 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Chooser 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data to display 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyDataRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a column here... 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyHeaders {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Continued on the next page) 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_GroupContinuedOnNextPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupContinuedOnNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a column header here to group by that column 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_GroupPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterCancelButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterOkButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Select All) 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterSelectAll {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (All) 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowAllItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Blanks) 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowBlanksItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Non blanks) 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowNonBlanksItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowNonBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beyond Next Month 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_BeyondNextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_BeyondNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earlier this Month 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_EarlierThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_EarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Month 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LastMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Week 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LastWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Later this Month 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LaterThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LaterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Month 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_NextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Week 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_NextWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Older 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Older {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Three Weeks Ago 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_ThreeWeeksAgo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_ThreeWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Three Weeks Away 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_ThreeWeeksAway {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_ThreeWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Today {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tomorrow 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Tomorrow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two Weeks Ago 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_TwoWeeksAgo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_TwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two Weeks Away 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_TwoWeeksAway {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_TwoWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Yesterday {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Form 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_PopupEditFormCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.PopupEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avg={0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Average {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avg of {1} is {0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Average_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Average_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count={0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Count {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max={0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Max {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max of {1} is {0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Max_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Max_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min={0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Min {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min of {1} is {0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Min_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Min_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum={0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Sum {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum of {1} is {0} 的本地化字符串。
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Sum_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Sum_OtherColumn", resourceCulture);
            }
        }
    }
}
