//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxScheduler_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxScheduler_v13_1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxScheduler_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_CaptionViewNavigator_Today {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.CaptionViewNavigator_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Day {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day(s) 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Days {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_DeleteRecurrentApt {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_DeleteRecurrentApt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show detail info 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_DetailInfo {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_DetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Error {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Every {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every weekday 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_EveryWeekday {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go To Date 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_GotoDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_GotoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Info {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t load {0} 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_LoadError {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 month(s) 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Months {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 occurrences 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Occurrences {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Of {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of  every 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OfEvery {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Recurring Item 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OpenRecurrentApt {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OpenRecurrentApt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press ESC to cancel operation 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OperationToolTip {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OperationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End by: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurenceRange_EndBy {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurenceRange_EndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No end date 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurenceRange_NoEndDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurenceRange_NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End after: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurenceRange_OccurrenceCount {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurenceRange_OccurrenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recur every 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurEvery {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurrence 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Recurrence {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Daily {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Monthly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Weekly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yearly 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Yearly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show more 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_ShowMore {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_The {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:D} &amp;ndash; {1:D} 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_ViewVisibleInterval_Format {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_ViewVisibleInterval_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Warning {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 week(s) on: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_WeeksOn {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_WeeksOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All day event 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_AllDayEvent {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_AllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonCancel {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonDelete {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dismiss 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonDismiss {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dismiss All 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonDismissAll {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonDismissAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonOk {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snooze 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonSnooze {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to delete all occurrences of the recurring appointment &quot;{0}&quot;, or just this one? 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is a recurring appointment. Do you want to open only this occurrence or the series? 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ConfirmEdit {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ConfirmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Date {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End time: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_EndTime {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Label {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Location {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This occurrence 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Occurrence {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Occurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Edit Form... 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_OpenEditForm {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_OpenEditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurrence 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Recurrence {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reminder 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Reminder {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Resource {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Save {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The series 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Series {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show in: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ShowIn {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ShowIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Snooze to be reminded again in: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_SnoozeInfo {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_SnoozeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_StartTime {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show time as: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Status {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject: 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Subject {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backward 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_TooltipViewNavigator_Backward {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.TooltipViewNavigator_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_TooltipViewNavigator_Forward {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.TooltipViewNavigator_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to Date 的本地化字符串。
        /// </summary>
        internal static string ASPxSchedulerStringId_TooltipViewNavigator_GotoDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.TooltipViewNavigator_GotoDate", resourceCulture);
            }
        }
    }
}
