//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxHtmlEditor_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxHtmlEditor_v13_1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxHtmlEditor_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Constrain Proportions On 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Alt_ConstrainProportions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Alt_ConstrainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constrain Proportions Off 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Alt_ConstrainProportionsOff {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Alt_ConstrainProportionsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonCancel {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonChange {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonInsert {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonOk {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonSelect {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Image 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Link 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeTableColumn_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeTableColumn_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply CSS 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandApplyCss {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandApplyCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back Color 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBackColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBold {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bullet List 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBulletList {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Center 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCenter {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Spelling 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCheckSpelling {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCheckSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCopy {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCut {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fore Color 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandForeColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Screen 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandFullscreen {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandIndent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandItalic {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Justify 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandJustify {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Left 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordered List 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandOrderedList {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outdent 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandOutdent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandOutdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPaste {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste from Word 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPasteRtf {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPasteRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPrint {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRedo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Format 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRemoveFormat {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Right 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strikethrough 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandStrikethrough {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscript 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandSubscript {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Superscript 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandSuperscript {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandSuperscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underline 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUnderline {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUndo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Link 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUnlink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Image... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_ChangeImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Link... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_ChangeLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_ChangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell Properties... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableCellProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Properties... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableColumnProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Properties... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Properties... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableRowProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableRowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The HTML content is invalid 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Table 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTable {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Column 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTableColumn {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Row 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTableRow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DesignViewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DesignViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Name 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_FontName {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Size 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_FontSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_HtmlViewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.HtmlViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create thumbnail 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_CreateThumbnail {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_CreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom size 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_CustomSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Description {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Height {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New image name 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_NewImageName {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_NewImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original image size 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_OriginalSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pixels 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Pixels {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Position {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionCenter {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left-aligned 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right-aligned 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Width {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Image 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter image web address 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_EnterUrl {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_EnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From your computer 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_FromLocal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_FromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the web (URL) 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_FromWeb {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_FromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More options 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_MoreOptions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image preview 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_Preview {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save file to server 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_SaveToServer {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_SaveToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke a dialog allowing you to select an image 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_SelectImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse your computer for the image file to upload 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_UploadInstructions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_UploadInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrap text around image 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_UseFloat {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_UseFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Link 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Properties 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_DisplayProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_DisplayProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail address 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Email {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail to 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_EmailTo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in new window 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_OpenInNewWindow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke a dialog allowing you to select a document 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_SelectDocument {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_SelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Subject {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Text {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToolTip 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Url {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Table... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Column to the Left 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableColumnToLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableColumnToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Column to the Right 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableColumnToRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableColumnToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Row Above 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableRowAbove {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Row Below 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableRowBelow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accessibility 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Accessibility {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alignment 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Center {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Left {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Right {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Appearance {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply to all cells in the table 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_ApplyToAllCell {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_ApplyToAllCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoFit to contents 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_AutoFitToContent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_AutoFitToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background color 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BgColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border color 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BorderColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border size 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BorderSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Both {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caption 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Caption {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell padding 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_CellPaddings {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_CellPaddings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell spacing 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_CellSpacing {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_CellSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Columns {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Custom {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equal column widths 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_EqualColumnWidths {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_EqualColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Column 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FirstColumn {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Row 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FirstRow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full width 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FullWidth {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Headers 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Headers {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Height {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_HorzAlignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_HorzAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Layout {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_None {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rows 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Rows {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Size 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Summary {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Bottom {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Middle 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Middle {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Top {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VertAlignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VertAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Width {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid URL format, or a file cannot be found using this URL 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InvalidUrlErrorText {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InvalidUrlErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Down 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_MergeTableCellDown {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.MergeTableCellDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Right 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_MergeTableCellHorizontal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.MergeTableCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paragraph 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Paragraph {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please paste inside the following box and hit OK. 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PasteRtf_Instructions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PasteRtf_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strip font family 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PasteRtf_StripFont {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PasteRtf_StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PreviewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PreviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field is required 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_RequiredFieldError {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The content of the editor cannot be empty 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_RequiredHtmlContentError {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.RequiredHtmlContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Office Open XML (.docx) 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsDocx {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to DOCX file and save it to a local disk 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsDocx_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsDocx_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIME HTML (.mht) 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsMht {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsMht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to MHT file and save it to a local disk 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsMht_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsMht_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Document (.odt) 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsOdt {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsOdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to ODT file and save it to a local disk 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsOdt_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsOdt_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portable Document (.pdf) 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsPdf {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to PDF file and save it to a local disk 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsPdf_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsPdf_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rich Text (.rtf) 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsRtf {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to RTF file and save it to a local disk 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsRtf_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsRtf_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plain Text (.txt) 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsTxt {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to TXT file and save it to a local disk 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsTxt_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsTxt_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SelectAll {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Document 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SelectDocument {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SelectImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split Horizontally 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SplitTableCellHorizontal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SplitTableCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split Vertically 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SplitTableCellVertical {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SplitTableCellVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell Properties... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableCellProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Properties... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableColumnProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Properties... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Properties... 的本地化字符串。
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableRowProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableRowProperties", resourceCulture);
            }
        }
    }
}
