//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxSpellChecker_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxSpellChecker_v13_1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxSpellChecker_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add to Dictionary 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_AddToDictionaryButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.AddToDictionaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_CancelButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change All 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeAllButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change To: 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeTo {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose which dictionary to use when checking your spelling. 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChooseDictionary {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChooseDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_CloseButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The spelling check is complete. 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_FinishSpellChecking {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.FinishSpellChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General options 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_GeneralOptions {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore All 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreAllButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore e-mails 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreEmails {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore words in MiXeDcAsE 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreMixedCase {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreMixedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore words with numbers 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreNumbers {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Once 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreOnceButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreOnceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore markup tags 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreTags {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore words in UPPERCASE 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreUppercase {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore URLs 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreUrls {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 International dictionaries 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_InternationalDictionaries {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.InternationalDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_Language {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (No Suggestions) 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_NoSuggestionsText {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.NoSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not in Dictionary: 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_NotInDictionary {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.NotInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OkButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options... 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OptionsButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spelling Options 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OptionsFormCaption {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OptionsFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Spelling 的本地化字符串。
        /// </summary>
        internal static string ASPxSpellCheckerStringId_SpellCheckFormCaption {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.SpellCheckFormCaption", resourceCulture);
            }
        }
    }
}
